uploads = []
outputs = []

[[generated]]
id = "AK8av7WXKprCqYJH8PBGL"
uri = "file://artifacts/noosfera/public/images/nft-castle-ai.png"
type = "image"
title = "ai fantasy castle purple night"

[[generated]]
id = "p6K-anhCqDzn_XDUJBdAe"
uri = "file://artifacts/noosfera/public/images/auth-hero.png"
type = "image"
title = "auth hero nft cosmic purple"
