uploads = []
outputs = []

[[generated]]
id = "AK8av7WXKprCqYJH8PBGL"
uri = "file://artifacts/noosfera/public/images/nft-castle-ai.png"
type = "image"
title = "ai fantasy castle purple night"

[[generated]]
id = "p6K-anhCqDzn_XDUJBdAe"
uri = "file://artifacts/noosfera/public/images/auth-hero.png"
type = "image"
title = "abandoned castle twilight landscape"

[[generated]]
id = "-YMGlkzpshIybwQqKH1Mz"
uri = "file://artifacts/noosfera/public/images/collage-1.png"
type = "image"
title = "bioluminescent jellyfish"

[[generated]]
id = "f4JwrsooC3K9eoEiSeYxG"
uri = "file://artifacts/noosfera/public/images/collage-2.png"
type = "image"
title = "neon data human silhouette"

[[generated]]
id = "IfxfYGVbOKSYHBOd5ty3M"
uri = "file://artifacts/noosfera/public/images/collage-3.png"
type = "image"
title = "aurora mountains night"

[[generated]]
id = "E-8fDiFQMy2gshnYJqlyF"
uri = "file://artifacts/noosfera/public/images/collage-4.png"
type = "image"
title = "mystical glowing forest"

[[generated]]
id = "Va03uflQSVJglYbX65tiZ"
uri = "file://artifacts/noosfera/public/images/collage-5.png"
type = "image"
title = "chromatic liquid metal"

[[generated]]
id = "YzSLvd4vv-AZODDuu4Y_0"
uri = "file://artifacts/noosfera/public/images/collage-6.png"
type = "image"
title = "cyberpunk tokyo night"

[[generated]]
id = "YWe0F-DGbHW-GUmPQJJVb"
uri = "file://artifacts/noosfera/public/images/collage-7.png"
type = "image"
title = "fantasy dragon mountains"

[[generated]]
id = "fHMmO8ZfffTB19ESay7oN"
uri = "file://artifacts/noosfera/public/images/collage-8.png"
type = "image"
title = "wolf moonlight forest"

[[generated]]
id = "kwPpIYkyV_hxZ0NNAFk5Y"
uri = "file://artifacts/noosfera/public/images/collage-9.png"
type = "image"
title = "ancient castle ruins ivy"

[[generated]]
id = "qsi8ZPEP47kMlhJXz2L6U"
uri = "file://artifacts/noosfera/public/images/collage-10.png"
type = "image"
title = "female warrior celestial armor"

[[generated]]
id = "JB_X_ED_g3KXFTHmGJiJk"
uri = "file://artifacts/noosfera/public/images/collage-11.png"
type = "image"
title = "bioluminescent tropical jungle"

[[generated]]
id = "wPg7tcw1ZldWTuuSwj8g5"
uri = "file://artifacts/noosfera/public/images/collage-12.png"
type = "image"
title = "coral reef magical underwater"

[[generated]]
id = "u1ilfv8WYedzf2IjD8bxk"
uri = "file://artifacts/noosfera/public/images/collage-13.png"
type = "image"
title = "cherry blossom lanterns night"

[[generated]]
id = "4p88pPqJABbOdtzlrshnH"
uri = "file://artifacts/noosfera/public/images/collage-14.png"
type = "image"
title = "magical oak tree fairy lights"

[[generated]]
id = "29klXm1xhLpRJ5wD_nRHC"
uri = "file://artifacts/noosfera/public/images/collage-15.png"
type = "image"
title = "cosmic lion galaxy portrait"

[[generated]]
id = "OWT6PTrr_cawfGvx_zE_r"
uri = "file://artifacts/noosfera/public/images/collage-16.png"
type = "image"
title = "samurai moonlit bamboo"

[[generated]]
id = "-jgoUDXCOjVWOtMKmSUkH"
uri = "file://artifacts/noosfera/public/images/collage-17.png"
type = "image"
title = "egyptian pharaoh golden aura"

[[generated]]
id = "cTPuUk2saKNY_CUIPbavU"
uri = "file://artifacts/noosfera/public/images/collage-18.png"
type = "image"
title = "fire phoenix volcanic eruption"

[[generated]]
id = "7wfbkeO3WffAkKb2aQOlt"
uri = "file://artifacts/noosfera/public/images/collage-19.png"
type = "image"
title = "mermaid underwater palace"

[[generated]]
id = "_s4f6HLd3nyi-trodCgtw"
uri = "file://artifacts/noosfera/public/images/collage-20.png"
type = "image"
title = "white tiger ice markings arctic"

[[generated]]
id = "h5fAxIAlfHcYFxkxmOBlI"
uri = "file://artifacts/noosfera/public/images/auth-R2-1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "5Txug9Z62kBIDmuU2w_hF"
uri = "file://artifacts/noosfera/public/images/auth-L3-1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "3g6wU2GtWyLbRnz715bDN"
uri = "file://artifacts/noosfera/public/images/auth-L3-2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Gf4oOe5WXtN0b_67ZFU7g"
uri = "file://artifacts/noosfera/public/images/auth-L3-3.png"
type = "image"
title = "generated_image"

[[generated]]
id = "2dxG0_0rPJAKThFoCMLLT"
uri = "file://artifacts/noosfera/public/images/auth-L3-4.png"
type = "image"
title = "generated_image"

[[generated]]
id = "y-E9OCnWQYgGuabVVM0FO"
uri = "file://artifacts/noosfera/public/images/auth-L3-5.png"
type = "image"
title = "generated_image"

[[generated]]
id = "kwr_vGzl3cRoCA8QuMqYq"
uri = "file://artifacts/noosfera/public/images/auth-L4-1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "TeW7uTiwM0msyOlgcvV8U"
uri = "file://artifacts/noosfera/public/images/auth-L4-2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "8fT_UCGKA_Ixdm7YyCoDu"
uri = "file://artifacts/noosfera/public/images/auth-L4-3.png"
type = "image"
title = "generated_image"

[[generated]]
id = "8OiglRuQO9dx3_eX7ppTe"
uri = "file://artifacts/noosfera/public/images/auth-L4-4.png"
type = "image"
title = "generated_image"

[[generated]]
id = "fHU6Yewb-4a7EliXP_DbN"
uri = "file://artifacts/noosfera/public/images/dragon-pricing.png"
type = "image"
title = "purple dragon pricing"

[[generated]]
id = "YM2KZ-yp9yiS8dzEH0Nul"
uri = "file://artifacts/noosfera/public/images/viking-warrior.png"
type = "image"
title = "viking-warrior-axe-runes"
