uploads = []
outputs = []

[[generated]]
id = "55VndfcJJYeKRp201lycG"
uri = "file://artifacts/noosfera/public/images/hero-main.png"
type = "image"
title = "colorful tiger art"

[[generated]]
id = "V49z3RiypO0x3Qpk2icZP"
uri = "file://artifacts/noosfera/public/images/hero-top.png"
type = "image"
title = "colorful owl art"

[[generated]]
id = "1u16RkWy1vNGwkCzt4_Bz"
uri = "file://artifacts/noosfera/public/images/hero-bottom.png"
type = "image"
title = "magical clock fruits art"

[[generated]]
id = "DwoHRIOV_s5W_zvh_oz_X"
uri = "file://artifacts/noosfera/public/images/nft-1.png"
type = "image"
title = "tree creature NFT art"

[[generated]]
id = "QmHLJVCL4jXiOr56nzwkW"
uri = "file://artifacts/noosfera/public/images/nft-2.png"
type = "image"
title = "retro NYC car NFT art"

[[generated]]
id = "gSnasNLRDGpqAHru9u4nd"
uri = "file://artifacts/noosfera/public/images/nft-3.png"
type = "image"
title = "skull fantasy NFT art"

[[generated]]
id = "hutL3NUBEXEPYOAz05QWn"
uri = "file://artifacts/noosfera/public/images/nft-4.png"
type = "image"
title = "crane bird NFT art"

[[generated]]
id = "k2yVggSnZKgX2iSzEXEl_"
uri = "file://artifacts/noosfera/public/images/nft-5.png"
type = "image"
title = "panda portal NFT art"

[[generated]]
id = "yuBYLuDEMXAAxp6f1vE6d"
uri = "file://artifacts/noosfera/public/images/nft-6.png"
type = "image"
title = "wolf aurora NFT art"

[[generated]]
id = "MgBwAZ93bNLDXQuespIxX"
uri = "file://artifacts/noosfera/public/images/nft-7.png"
type = "image"
title = "dragon fire NFT art"

[[generated]]
id = "yfg6LnWxuP45M7nkDXtUN"
uri = "file://artifacts/noosfera/public/images/nft-8.png"
type = "image"
title = "mermaid ocean NFT art"

[[generated]]
id = "jtYik1m4p0Kc6XZ5NdrwA"
uri = "file://artifacts/noosfera/public/images/nft-9.png"
type = "image"
title = "samurai NFT art"

[[generated]]
id = "2TkJY7cE-Uti_ZmoQ16qT"
uri = "file://artifacts/noosfera/public/images/nft-10.png"
type = "image"
title = "phoenix NFT art"

[[generated]]
id = "qB7MfS81SvSAGZwe_cPPO"
uri = "file://artifacts/noosfera/public/images/nft-ghost.png"
type = "image"
title = "ghost fantasy creature"
